<?php
// Retrieve the selected city from cookie or display default text.
$city = $block->getCookie('selected_city') ?: __('Your city');
?>
<div id="location-menu" style="cursor:pointer;">
    <i class="fa fa-map-marker" aria-hidden="true"></i>
    <span id="location-city"><?= $city ?></span>
</div>

<!-- Modal window that displays the list of cities -->
<div id="location-modal" style="display:none;">
    <div class="modal-content">
        <h2><?php echo __('Choose your city'); ?></h2>
        <div class="city-dropdown">
            <select id="city-select" size="10" style="height: auto !important; max-height: 150px;">
            </select>
        </div>
        <div id="city-error" style="display:none;color:red;"></div>
    </div>
</div>

<script type="text/javascript">
    require(['Perspective_NewGeoLocation/js/location'], function(location) {
        location.init();
    });
</script>
