<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2022-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/**
 * @experimental
 *
 * This template may change in backward incompatible ways without notice, since the speculation-rules browser API it depends on is experimental, too.
 */

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
?>
<script>
    if (HTMLScriptElement.supports && HTMLScriptElement.supports('speculationrules')) {
        const specScript = document.createElement('script');
        specScript.type = 'speculationrules';
        specRules = {
            'prerender': [{
                'where': {
                    'and': [
                        { 'href_matches': '/*.html' },
                        { 'not': {'selector_matches': '.do-not-prerender'}}
                    ]
                },
                'eagerness': 'moderate'
            }]
        };
        specScript.textContent = JSON.stringify(specRules);
        document.body.append(specScript);
    }
</script>
